### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by DavidBerdik** [furplag/Herobrine#3]
Hello furplag,

Have you completed adding support for 1.20.2? If so, could you submit a PR with your changes to my repo so that I don't have to go through the tedious process of updating it myself?

Thank you,
David

**Comment by furplag** [comment]
Hello @DavidBerdik .
I had create [PR#7](https://bitbucket.org/David-B/herobrine-2/pull-requests/7) into your repository .

regards, thank you for your great work .

**Comment by DavidBerdik** [comment]
Thank you! I've just merged your pull request and will try to publish the update for it soon!
